services:
  ldap:
    image: 389ds/dirsrv:2.4
    hostname: ldap
    container_name: ldap
    healthcheck:
      test: ["CMD", "/usr/lib/dirsrv/dscontainer", "-H"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 120s
    environment:
      DS_DM_PASSWORD: password
      DS_SUFFIX_NAME: dc=example,dc=com
    volumes:
      - ./ldap/init:/init
    entrypoint: /init/entrypoint.sh

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    depends_on:
      ldap:
        condition: service_healthy
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    volumes:
      - ./keycloak/init:/init
    entrypoint: /init/entrypoint.sh